name: Dev CI

# Least privilege
permissions: {}
# CI pipeline runs only on main branche
# Runs when there is a pull request
# Allows for manual triggers in the UI
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Creates a pipeline with a unique name either with a
# the pull request number or with a commit hash
# there can only be one pipeline running meaning multiple pushes cancel
# the previous one.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
# Build runner
  npm-cache:
    # create matrix for windows, mac and linux
    # Break out this job so it's less cluttered
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # add windows support
          # Add both .npm as well as node_modules, since these are the same it's no issue
          path: |
            ~/.npm 
            ./node_modules 
          key: ${{ runner.os }}-cache-${{ env.cache-name }}
          # restore-keys can be used if a push comes from another repo

      - name: Set cache name as output
        run: echo "cache_name=${{ env.cache-name }}" >> $GITHUB_OUTPUT

      # used to compare caches from branches
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  dev: 
    runs-on: ubuntu-latest
    needs: npm-cache

    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.npm 
            ./node_modules
          key: ${{ runner.os }}-cache-${{ needs.npm-cache.outputs.cache_name }} 

      - name: Check lint
        run: npm run lint:check

      - name: Check format
        run: npm run format:check

      - name: Test unit
        run: npm run test:dev

  build:
    runs-on: ubuntu-latest
    needs: npm-cache

    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.npm 
            ./node_modules
          key: ${{ runner.os }}-cache-${{ needs.npm-cache.outputs.cache_name }} 

      - name: Check exports
        run: npm run check-exports


  
